### ISSUE TITLE
Milestone 2 - Development

### ISSUE THREAD

**Issue by krishna-patel-55** [krishna-patel-55/BookNook#3]
- [ ] Environment Setup
- [ ] Basic features implementation
- [ ] Advance features / data exchange
- [ ] Front-end/UI integration
